### PR TITLE
Fix #33: Lighter line numbers.

### LINKED ISSUE #33: Margin line numbers color
Hello,

I use your theme, and like it.
However, is it possible to set the color of the line numbers in the editor margin a little more lighter to increase readibility of them ?

Thank's for your answer.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
For https://github.com/Harry-Hopkinson/vim-vscode-theme/issues/33

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
Before:
Screenshot 2024-04-19 at 20 47 49

After:
Screenshot 2024-04-19 at 20 47 56

**Comment by Harry-Hopkinson** [comment]
@ChristopheDassise does that look better?

**Comment by Harry-Hopkinson** [comment]
It does not show up that well on a screenshot but is noticeably lighter in vscode.

**Comment by ChristopheDassise** [comment]
I'm trying with this :
"editorLineNumber.foreground": "#8a7c71"

**Comment by Harry-Hopkinson** [comment]
I have changed it now to 8a7c71 - how does it look?

**Comment by ChristopheDassise** [comment]
2024-04-20_13h49_16

It looks good for me with this color now (-:

Have a nice day

**Comment by ChristopheDassise** [comment]
image

It looks good for me with this color (-:

Have a nice day

**Comment by Harry-Hopkinson** [comment]
Thanks, I will release the new version now.

**Pull request merged**
