### PR TITLE
Update vim-dark-hard.json

### PR DESCRIPTION
**Pull request by Donniedarko45**

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
I don't think mono is a font style - do you mean bold?

**Comment by Donniedarko45** [comment]
Actually I want Ubuntu mono font style in the comment part

**Comment by Harry-Hopkinson** [comment]
Aaah - I see...

**Comment by Donniedarko45** [comment]
Haha, thanks!

**Comment by Harry-Hopkinson** [comment]
Can you upload a screenshot of the before and after please - I do not have the mono font installed so cannot test these changes.

**Comment by Donniedarko45** [comment]
Screenshot 2024-04-17 022715
before 
and the font I want is 
Screenshot 2024-04-17 023127
not able to see the changes in vs
Do you wan the font style?

**Comment by Harry-Hopkinson** [comment]
If you want to change your font in vscode you can edit your settings.json file to your font, have you done that?

https://www.iorad.com/player/2201878/VS-Code----How-to-change-your-Visual-Studio-Code-font-family#trysteps-5

**Comment by Donniedarko45** [comment]
Yess don't know why the comment part is not changing nevertheless, it is
also good thanks. Vim theme is 🔥

**Comment by Harry-Hopkinson** [comment]
Did it work when you changed your font in the vscode settings?

**Comment by Donniedarko45** [comment]
nah but i made a new css file where i write a font-style of comments section  then added the path of css file  into settings.json and its working
Screenshot 2024-04-20 011716

**Comment by Harry-Hopkinson** [comment]
Great work! Looks great. Can this PR be closed then?

**Comment by Donniedarko45** [comment]
yess, thanks for help

**Comment by Harry-Hopkinson** [comment]
No worries - enjoy using the theme.

**Pull request closed without merging**
