### PR TITLE
Added Menu Separator Background

### PR DESCRIPTION
**Pull request by monicfenga**
Finally found it!

### CODE REVIEW

**Comment by monicfenga** [comment]
Please use your side of the `vim-deep-dark.json` file, I didn't touch this

**Comment by Harry-Hopkinson** [comment]
Reverting changes to vim-deep-dark.json

**Comment by Harry-Hopkinson** [comment]
@monicfenga do the change still look okay. I have done some cleanup on the vim-deep-dark.json

**Comment by Harry-Hopkinson** [comment]
@monicfenga thank you for your contribution!

**Pull request merged**
