### PR TITLE
Stick Pane Themes 

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
For #35

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
@yay How do the following themes look?

Screenshot_20240914_185532
Screenshot_20240914_185547
Screenshot_20240914_185558
Screenshot_20240914_185607
Screenshot_20240914_185607-1
Screenshot_20240914_185618
Screenshot_20240914_185630
Screenshot_20240914_185640

**Comment by yay** [comment]
It looks beautiful! Thank you.

But I can only see the border on screenshots #1 and #3.
Also, I'm assuming this is the normal state of the sticky pane, how about the hovered one?

**Comment by Harry-Hopkinson** [comment]
Ah nice catch, I will make the border blend in nicer and show photos when hovered.

**Comment by Harry-Hopkinson** [comment]
Screenshot 2024-09-16 at 20 17 28
Screenshot 2024-09-16 at 20 17 55
Screenshot 2024-09-16 at 20 18 08
Screenshot 2024-09-16 at 20 18 25
Screenshot 2024-09-16 at 20 18 37
Screenshot 2024-09-16 at 20 18 50
Screenshot 2024-09-16 at 20 19 02

**Comment by Harry-Hopkinson** [comment]
As you can see, there is a noticeable different between both states so you can easily see if you are hovering or not.

**Comment by yay** [comment]
Sorry it took me a while to respond.

I think I should clarify what I meant by the border. These are screenshots from https://github.com/Harry-Hopkinson/vim-vscode-theme/pull/36#issuecomment-2351085027:

IMO, this first dark theme nails everything perfectly. Here we can see the border:
367535282-dbfd0b1f-ef36-41cd-8377-ba7b70c66d87

And here the border is missing:
367535290-94ee6c97-2849-4486-9bff-0cd871b69f4c

I would expect the border to be present in all variants. For example:
Screenshot 2024-09-19 at 8 13 16 PM

And the sticky pane's highlight style to have a darker background. Just like the selected line in the editor becomes darker than the rest of them.
Screenshot 2024-09-19 at 8 12 52 PM

Not necessarily the same colors, but probably some derivates of the regular color. For example where the L component in HSL representation is X% smaller -- and for dark themes, bigger (which is already the case for this dark theme here).

**Comment by Harry-Hopkinson** [comment]
Ah, I see what you mean now. I will add it straight away.

**Comment by yay** [comment]
I love it! Thank you so much!

**Comment by Harry-Hopkinson** [comment]
Great to hear! Releasing it as a new version now.

**Pull request merged**
